# This config file for Travis CI utilizes https://github.com/ros-planning/moveit_ci/ package.
os: linux
dist: bionic  # distro used by Travis, moveit_ci uses the docker image's distro
sudo: required
services:
  - docker
language: cpp
cache: ccache
compiler: gcc

env:
  global:
    - MOVEIT_CI_TRAVIS_TIMEOUT=85  # Travis grants us 90 min, but we add a safety margin of 5 min
    - ROS_DISTRO=foxy
    - ROS_REPO=ros
    - CXXFLAGS="-Wall -Wextra -Wwrite-strings -Wunreachable-code -Wpointer-arith -Wredundant-decls"
    - WARNINGS_OK=false

jobs:
  fast_finish: true
  include:
    - name: "[Foxy] - clang-format, ament_lint"
      env: TEST="clang-format ament_lint"
    - name: "[Foxy] - code-coverage"
      env: TEST=code-coverage
    - name: "[Foxy] - gcc (build,test)"
      env: ROS_DISTRO=foxy
    - name: "[Foxy] - clang (build,test,clang-tidy-fix)"
      compiler: clang
      # test_ikfast_plugins takes ~10 minutes: include here to keep the main jobs shorter
      env: TEST=clang-tidy-fix
           CXXFLAGS="-Wall -Wextra -Wwrite-strings -Wunreachable-code -Wpointer-arith -Wredundant-decls -Wno-overloaded-virtual"
  allow_failures:
    - env: TEST=code-coverage

before_script:
  - git clone -q -b ros2 --depth=1 https://github.com/ros-planning/moveit_ci.git .moveit_ci

script:
  - .moveit_ci/travis.sh
